### PR TITLE
Serializing harpoon

### PR DESCRIPTION
**Pull request by Ailrun**
__The target branch of this PR is `harpoon/holes`, not `master`!__

This PR implements serialization (or saving) function for harpoon.
Current state reset is unstable, i.e., does not preserve the session order, the theorem order, and the subgoal order in the state. However, it still preserves the current session/theorem/subgoal.

### CODE REVIEW

**Comment by Ailrun** [comment]
We should also save finished proofs/sessions automatically when they are finished.

**Comment by tsani** [comment]
Heads up @Ailrun, the PR doesn't pass travis because of trailing whitespace. Since we now forbid trailing whitespace in general I have added automatic trimming in my emacs config. I suggest you do the same too.

**Comment by tsani** [comment]
Also the PR looks good to me, so I'll be merging it soon. There's just one thing I want to refactor first: there are now at least three different places in the codebase where we perform the same signature loading logic. I'm changing the `Cfg` module to `Load` and moving all signature loading logic there. I'll add both of these patches to the `serializing-harpoon` branch if that's OK with you.

**Comment by Ailrun** [comment]
Adding some ways to guarantee whitespace problem is a good idea.
I might try something with git hook.

**Comment by Ailrun** [comment]
Now it preserves current session/theorem/subgoal

**Comment by Ailrun** [comment]
@tsani Now it preserves current session/theorem/subgoal

**Comment by Ailrun** [comment]
Is it OK to merge this? or...?

**Comment by tsani** [comment]
So I actually want to wait to merge this since tests don't pass.
Basically, once jake-wip is done (i.e. I get tests to pass on it) I'll incorporate those commits into serializing-harpoon and then merge serializing-harpoon to harpoon-holes, and harpoon-holes to master.

**Comment by tsani** [comment]
This has been effectively incorporated into master as of today.

**Pull request closed without merging**
