### PR TITLE
Automated proof-search rebase 2

### PR DESCRIPTION
**Pull request by sjjs7**
Notable changes:

- Add support to split/invert on variables
- solve substitution lemmas using assumptions in Delta
- blurring/lemma application
- changes to I.H. generation
- auto-tactics (auto-invert-solve and inductive-auto-solve)

### CODE REVIEW

**Comment by MartyO256** [comment]
The failing test `./t/harpoon/poplmark-reloaded/props.input` boils down to the following Beluga signature and Harpoon inputs:
```
%coverage

LF ty : type =
   | base : ty
   | arr  : ty -> ty -> ty
;
--name ty T.

LF tm : ty -> type =
   | abs : (tm A -> tm B) -> tm (arr A B)
   | app : tm (arr A B) -> tm A -> tm B
;
--name tm M.

schema cxt = tm A;

LF step : tm A -> tm A -> type =
   | rbeta : step (app (abs M) N) (M N)
   | rabs  : ({x : tm A} step (M x) (M' x)) -> step (abs M) (abs M')
   | rappl : step M M' -> step (app M N) (app M' N)
   | rappr : step N N' -> step (app M N) (app M N')
;

% Accessibility definition
inductive Sn : (g: cxt) {M: [g |- tm A[]]} ctype =
   | Acc : {g:cxt}{A : [ |- ty]}{M : [g |- tm A[]]}
         ({M' : [g |- tm A[]]} {S: [g |- step M M']} Sn [g |- M'])
      -> Sn [g |- M]
;
```

```
Sn-appl
(g : cxt) {M : [g |- tm (arr A[] B[])]} {N : [g |- tm A[]]} Sn [g |- app M N] -> Sn [g |- M]
2

split x
suffices by Acc toshow _
solve Sn-appl _ _ (x1 _ [_ |- rappl S])
```
The recursive call to `Sn-appl` fails because the induction hypothesis it requires comes from `let cIH0 = Total.wf_rec_calls cD cG mfs in (* ... *)` which was removed in `tactic.ml`.

Before:

https://github.com/Beluga-lang/Beluga/blob/520c41534820e12a52d640f3151480e790baa17e/src/harpoon/tactic.ml#L394-L396

After:

https://github.com/Beluga-lang/Beluga/blob/424888b911a603dca7dadddec9882b70efbfd59c/src/harpoon/tactic.ml#L396-L398

Reverting that change fixes the `./t/harpoon/poplmark-reloaded/props.input` test, but causes `auto-invert-solve` test cases to fail instead.

That notwithstanding, `auto-invert-solve` tests are incorrectly succeeding. The CI pipeline uses `make all-test` rather than `make test`. This is far from ideal, but removing the flags `--no-save-back --stop` from `./TEST.sh` reveals failing test cases:

https://github.com/Beluga-lang/Beluga/blob/424888b911a603dca7dadddec9882b70efbfd59c/TEST.sh#L286

Indeed, programs generated by `auto-invert-solve` introduce unbound variables, like `T2` in the following:
```
{ E : ( |- exp), V : ( |- exp), T : ( |- tp)
| x : [ |- eval E V], u : [ |- oft E T]
; split x as
  case ev_app:
  { E1 : ( |- exp),
    E3 : ( |- exp),
    V : ( |- exp),
    T : ( |- tp),
    T1 : ( |- tp),
    E2 : (x : exp |- exp),
    E4 : ( |- exp),
    F : ( |- eval E1 (lam T1 (\x. E2))),
    F1 : ( |- eval E3 E4),
    F2 : ( |- eval (E2[E4]) V)
  | x : [ |- eval (app E1 E3) V], u : [ |- oft (app E1 E3) T]
  ; solve
      let [ |- D] = u in
      pres [ |- _] [ |- _] [ |- T] [ |- F2]
        (let [ |- tp_app D1 D2] = [ |- D] in
          let x1 = pres [ |- _] [ |- _] [ |- T2] [ |- F1] [ |- D1] in
          let y2 = pres [ |- _] [ |- _] [ |- arrow T2 T] [ |- F] [ |- D2] in
          let [ |- D37] = y2 in
          let [ |- D38] = x1 in
          let [ |- tp_lam (\x. \z. D39)] = [ |- D37] in
          let z3 = pres [ |- _] [ |- _] [ |- T] [ |- F2] [ |- D39[E4, D38]] in
          let [ |- D124] = z3 in [ |- D39[E4, D38]])
  }
% ...
}
```

**Comment by MartyO256** [comment]
Are MQueries defunct, or are they still a planned feature? Since I'm revising the parser in a separate branch, I need to know whether or not to remove `MQuery` from the external syntax.

**Comment by sjjs7** [comment]
MQueries have been removed.

**Comment by sjjs7** [comment]
Yes, we are aware that some of the proofs produced by `auto-invert-solve` have in them unbound meta-variables. These proofs can be fixed by swapping said variables with an underscore. This isn't a problem with the tactic but with the way cases are produced during a split/induction. There is not yet a way to know which variables are explicit/implicit after a split. Currently, Beluga marks all meta-variables as explicit (though that is not the case). Other than this issue, did you see any other problems arise in the proofs? 

Regarding the part I took out in tactic.ml, it was at fault for producing the incorrect induction hypotheses that I found. These "bad" propositions caused the search-loop in logic.ml to fail. I could not think of a way to filter out said incorrect I.H.'s because some would be well-formed so the filtering would need to be more clever than simply checking syntax. I thought it simpler to remove, but yes that causes the prop.input example to fail.

**Comment by sjjs7** [comment]
With the merge of commit # afe6bdeacefac55df4fa814eea14b7c0b2caae25 (aps-rebase2-review into aps-rebase2), a number of bugs have been solved, including:
- unbound mvars appearing in the final Beluga term: once a Beluga term has been constructed, the term is parsed to ensure there are no unbound mvars present. This involves correcting the plicites of variables in Delta after a split/ inversion has been made.
- I.H. schemas being left out: the Harpoon tactic split has been reverted and fixed. I did fix a bug- that was originally, if we conducted induction on a variable in Gamma, we would mark that assumption (with the branch's meta-sub applied to it) as smaller, when in fact it is not. That assumption is now marked as not smaller- therefore there are no I.H. schemas created that refer to it. In cgSolve within logic.ml, when the solver takes a query from Harpoon, we remove any I.H. schemas that refer to variables in Gamma. Otherwise, the solver can construct ill-formed calls to the I.H., and currently there is no way to check that those calls are valid. So, for simplicity those schemas are omitted.
- when appealing to an I.H. within the solver cgSolve, we can only pass explicit mvars as arguments to the uninstantiated variables of the call- this ensures that during type reconstruction, there is enough info to correctly reconstruct the type
- in unify.ml, we can solve more complex unification problems:
Given some mvar:         cD |- u[^0],    we need to find an instantiation for u s.t.    cD' ; Psi |- u[^n, M1, ..., Mk] where cD' |- Psi and cD' |- [^n, M1, ..., Mk] : cD
we have that under cD' and Psi, 
u[^n, M1, ..., Mk]  = Mi   (i in {1,..., k})
therefore unify u with MVar(Offset (k - i + 1))

**Comment by sjjs7** [comment]
@MartyO256 , are there other tests failing from using `auto-invert-solve`?

**Comment by MartyO256** [comment]
`./t/harpoon/bwd_closed_auto_invert.input` is the only test that fails when using `auto-invert-solve`.

**Pull request merged**
