### PR TITLE
Added TextMate syntax bundle

### PR DESCRIPTION
**Pull request by marcelgoh**
Added syntax highlighting support for use with TextMate. The bundle can also be imported into various other text editors, including GitHub's own syntax highlighter. In the future, this bundle could be used to add Beluga to GitHub's recognised languages.

### CODE REVIEW

**Comment by pientka** [comment]
This branch does not pass travis, i.e. it does not build with OCaml 4.06.1, 4.05, 4.04. Please make sure your branch passes travis and ask for another pull request.

Brigitte

**Comment by adhameer** [comment]
The Travis build was broken for unrelated reasons. bbdd7ff should fix it, and then this branch should pass. I don't think there's anything in this change that would affect the build.

**Comment by tsani** [comment]
@marcelgoh if you rebase on top of master your build should pass since @adhameer fixed the Travis build.

**Comment by marcelgoh** [comment]
Thanks for the help everyone! I believe it works now.

**Pull request merged**
